Repository prgrms-aibe-devcourse/AIBE1-Project2-Team07-Frontend, pull requests merged in 2025-05, with the labels that each got.

#8 feature/trainer-profile, feature/trainer-list 완료
  public/common.html
  public/images/cat.png
  public/images/cat1.jpeg
  public/images/logo.png
  public/images/objects.jpg
  public/javascripts/trainer-list.js
  public/javascripts/trainer-profile-modal.js
  public/javascripts/trainer-profile.js
  public/stylesheets/common.css
  public/stylesheets/trainer-list.css
  public/stylesheets/trainer-profile-modal.css
  public/stylesheets/trainer-profile.css
  public/trainer-list.html
  public/trainer-profile.html
Labels: 🌟 기능 추가, 🎨 프론트엔드

#11 refactor: 네비게이션 바 반응형 개선
  public/common.html
  public/javascripts/common.js
  public/stylesheets/common.css
Labels: ♻️ 리팩터링, 🎨 프론트엔드, 🐛 버그

#14 refactor: 네비게이션 바 링크 수정
  public/common.html
Labels: ♻️ 리팩터링, 🎨 프론트엔드

#16 훈련사 마이페이지 완료
  public/javascripts/trainer-mypage.js
  public/stylesheets/trainer-mypage.css
  public/stylesheets/user-mypage.css
  public/trainer-mypage.html
Labels: 🌟 기능 추가, 🎨 프론트엔드, 🚨 긴급

#19 feat: 프로필 이미지 업로드 기능 구현
  public/images/icons/camera.svg
  public/javascripts/trainer-mypage.js
  public/javascripts/user-mypage.js
  public/stylesheets/trainer-mypage.css
  public/stylesheets/user-mypage.css
  public/user-mypage.html
Labels: 🌟 기능 추가, 🎨 프론트엔드

#23 ci: 워크플로우 관련 파일 추가
  .dockerignore
  .github/workflows/build_image.yml
  .github/workflows/main.yml
  Dockerfile
Labels: ⏳ 보통, 🧹 기타 작업

#25 refactor: 메인페이지 리팩터링
  public/home.html
  public/images/temp.jpg
  public/javascripts/home.js
  public/stylesheets/home.css
Labels: ⏳ 보통, ♻️ 리팩터링, 🎨 프론트엔드

#29 훈련사 등업 모달 기능, 훈련사 프로필 재정의
  public/javascripts/trainer-mypage.js
  public/javascripts/user-mypage-modal.js
  public/javascripts/user-mypage.js
  public/stylesheets/user-mypage-modal.css
  public/user-mypage.html
Labels: 🌟 기능 추가, 🎨 프론트엔드, 🚨 긴급

#32 훈련사 프로필 수정 기능 완료
  public/javascripts/trainer-edit-modal.js
  public/javascripts/trainer-profile.js
  public/stylesheets/trainer-edit-modal.css
  public/stylesheets/trainer-profile-modal.css
  public/stylesheets/trainer-profile.css
  public/trainer-profile.html
Labels: 🌟 기능 추가, 🎨 프론트엔드, 🚨 긴급

#34 상담, 방문 클릭 시 모달로 이동
  public/javascripts/advice-request-modal.js
  public/javascripts/trainer-list.js
  public/javascripts/trainer-profile.js
  public/stylesheets/advice-request-modal.css
  public/trainer-list.html
  public/trainer-profile.html
Labels: ⏳ 보통, 🌟 기능 추가, 🎨 프론트엔드

#37 방문상담, 영상상담 분류 완료
  public/javascripts/trainer-list.js
  public/javascripts/trainer-profile.js
  public/trainer-list.html
  public/trainer-profile.html
Labels: ⏳ 보통, 🎨 프론트엔드, 🐛 버그

#38 사용자 리뷰 탭 추가
  public/javascripts/user-advice.js
  public/javascripts/user-mypage.js
  public/stylesheets/user-advice.css
  public/user-mypage.html
Labels: 🌟 기능 추가, 🎨 프론트엔드, 🚨 긴급

#39 feat: 소셜 로그인, 토큰 저장
  app.js
  package-lock.json
  package.json
  public/common.html
  public/community-post.html
  public/community-write.html
  public/community.html
  public/javascripts/common.js
  public/javascripts/community.js
  public/login.html
  public/stylesheets/common.css
  routes/auth.js
Labels: 🌟 기능 추가, 🚨 긴급

#40 경로, common 수정
  public/community-post.html
  public/community-write.html
  public/community.html
  public/trainer-list.html
  public/trainer-mypage.html
  public/trainer-profile.html
  public/user-mypage.html
Labels: 🎨 프론트엔드, 🐛 버그

#47 파일오류 해결 + 매칭 연결 완료(파일전송제외)
  public/javascripts/advice-request-modal.js
  public/trainer-profile.html
Labels: 🌟 기능 추가, 🎨 프론트엔드, 🚨 긴급

#58 사용자 마이페이지 백엔드 연동 완료
  public/javascripts/user-advice.js
  public/javascripts/user-mypage.js
  public/user-mypage.html
Labels: 🌟 기능 추가, 🎨 프론트엔드, 🚨 긴급

#64 관리자 승인, 거부 페이지+백엔드 연동
  public/cert.html
  public/javascripts/cert.js
  routes/index.js
Labels: 🌟 기능 추가, 🎨 프론트엔드, 🚨 긴급

#66 상담상세보기 사진추가 + 코드정리
  public/cert.html
  public/javascripts/cert.js
  public/javascripts/user-mypage.js
Labels: ♻️ 리팩터링

#70 admin 사용자 탈퇴, 역할변경 완료
  app.js
  public/admin-cert.html
  public/admin-comment.html
  public/admin-post.html
  public/admin-user.html
  public/admin.html
  public/javascripts/admin-cert.js
  public/javascripts/admin-post.js
  public/javascripts/admin-user.js
  routes/admin.js
  routes/index.js
Labels: ⏳ 보통, 🌟 기능 추가, 🎨 프론트엔드

#79 최종 어드민 완료
  public/admin-post.html
  public/javascripts/admin-post.js
  public/javascripts/user-mypage.js
Labels: ♻️ 리팩터링, 🎨 프론트엔드

#85 최종 디자인 수정
  public/community.html
  public/javascripts/trainer-list.js
  public/trainer-list.html
Labels: 🎨 프론트엔드
